name: lwsspy
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.7
  - ipython
  - flake
  - pytest
  - matplotlib==3.2.1
  - numpy
  - mypy
  - scipy
  - cartopy
  - mpi4py
  - h5py
  - obspy
  - pyasdf
  - pooch
  - xarray
  - pip
  - pip:
    - pyyaml
    - sphinx
    - sphinx_rtd_theme
    - git+git://github.com/wjlei1990/pyflex.git@merge