[job]
system = ["nnodes.job", "Summit"]
name = "cmtinversion"
nnodes = 70
account = "GEO111"
walltime = 120.0
gap = 15.0
debug = true
node_splittable = false

[root]
task = ["lwsspy.gcmt3d.ioi.nnodes.inversion", "main"]
task_nnodes = 1
inputfile = "/ccs/home/lsawade/events/gcmt3d/input.yml"
max_events = 7
#eventid = "C051200C"
nproc = 20


[root.specfem]
mpis = 24
gpus = 0.25
timeout = 1200 # in seconds 