[job]
system = ["nnodes.job", "Tiger"]
name = "cmtinversion"
nnodes = 4
account = "GEO111"
walltime = 60.0
gap = 2.0
debug = true

[root]
task = ["lwsspy.gcmt3d.ioi.nnodes.inversion", "main"]
task_nnodes = 1
inputfile = "/ccs/home/lsawade/events/gcmt3d/input.yml"

[root.specfem]
mpi = 24
gpus = 0.25