[job]
system = ["nnodes.job", "Tiger"]
name = "source"
nnodes = 1
account = "GEO111"
walltime = 120.0
gap = 2.0
debug = true

[root]
task = ["lwsspy.gcmt3d.ioi.nnodes.source", "main"]
task_nnodes = 1
inputfile = "/home/lsawade/lwsspy/lwsspy.gcmt3d/src/lwsspy/gcmt3d/ioi/input.yml"
