[job]
system = ["nnodes.job", "Local"]
name = "download"
nnodes = 1
account = "GEO111"
walltime = 120.0
gap = 5.0
debug = true
node_splittable = true

[root]
task = ["lwsspy.gcmt3d.ioi.nnodes.download", "main"]
task_nnodes = 1
inputfile = "/ccs/home/lsawade/events/download/input.yml"
max_downloads = 1
download_mpi = 0
events_per_chunk = 1
eventid = "C051200C"
